version: "3"
  
services:
    
    api:
        image: orion/api-hello-world  
        working_dir: /app
        ports:
            - "5001-5200:5000"
        deploy:
          resources:
            limits:
              cpus: '0.08'
              memory: 2G
            reservations:
              cpus: '0.02'
              memory: 512m
        
        environment:
          - TZ=Asia/Dhaka
          - DBConnectionString=Server=172.16.219.82;Database=LoadBalancer;User ID=sa;password=Techvision123?;Pooling=true;Max Pool Size=200;|Server=172.16.219.83;Database=LoadBalancer;User ID=sa;password=Techvision123?;Pooling=true;Max Pool Size=200;
          - DockerName=api1   